server:
  port: 8000

spring:
  profiles:
    group:
      dev: dev
      prod: prod
    active: prod

  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh

---
spring:
  config:
    activate:
      on-profile: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: local
    password: local

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
