server:
  port: 8000

spring:
  profiles:
    group:
      dev: dev
      prod: prod
    active: prod

  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh

---
spring:
  config:
    activate:
      on-profile: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: local
    password: local

  cloud: # prod - cloud config
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/api/v1/members
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/api/v1/member/verification-email/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/api/v1/member/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
